# Theme and Plugins
remote_theme: pages-themes/primer@v0.2.0
plugins:
 - jekyll-remote-theme
# Repository Metadata
title: "Maven Pixar Challenge: Analyzing Pixar's Legacy Through Data"
description: "An interactive Power BI analysis exploring Pixar's financial performance, audience engagement, and storytelling patterns. This project uncovers insights into the factors behind Pixar's biggest hits, box office success, and critical reception over the past 30 years."
author: "Jan Aeron Abrahan"
github_username: "aeronabrahan"
# Navigation Settings
show_downloads: true
include:
 - README.md
 - assets/datasets
 - assets/images
 - assets/pbi
# Repository Settings
repository: "aeronabrahan/Maven-Pixar-Challenge
"
url: "https://github.com/aeronabrahan/Maven-Pixar-Challenge"
# SEO and Social Sharing
social:
 name: "Jan Aeron Abrahan"
 links:
   - "https://github.com/aeronabrahan"
   - "https://linkedin.com/in/jagabrahan"
# Custom Options
markdown: kramdown
permalink: pretty
