# Theme and Plugins
remote_theme: "jekyll/minima@1e8a445"
plugins:
 - jekyll-remote-theme
# Repository Metadata
description: "https://www.linkedin.com/in/jagabrahan/"
author: "Jan Aeron Abrahan"
github_username: "aeronabrahan"
# Navigation Settings
show_downloads: true
include:
 - README.md
 - assets/datasets
 - assets/images
 - assets/pbi

# SEO and Social Sharing
social:
 name: "Jan Aeron Abrahan"
 links:
   - "https://github.com/aeronabrahan"
   - "https://linkedin.com/in/jagabrahan"

